version: "3.8"
services:
  springboot-app:
    image: pmg3858/dgswc-inside-server:latest
    container_name: dgswc-inside
    ports:
      - "8080:8080"
    volumes:
      - /tmp
    restart: unless-stopped
    environment:
      - DATABASE_URL=jdbc:mysql://dgswc-inside.c6ne6qs445x4.us-east-1.rds.amazonaws.com
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=test1206